apiVersion: v2
name: iam-service
description: A Helm chart for Kubernetes
version: 0.0.4

dependencies:
  - name: postgresql
    version: "16.1.1" # version of the postgres chart
    repository: "https://charts.bitnami.com/bitnami"
    condition: db.postgresNeedsProvision
