dataloader:
  enabled: true
  data:
    tenants:
      - tenant1
      - tenant2
  migration:
    dumpIamDataToFga: false
  iamData:
    groups:
      - displayName: Member
        technicalName: projectMembers
        description: Standard role
        entity: project
        policies:
          - projectMember
          - githubMember
      - displayName: Owner
        technicalName: projectAdmins
        description: Can manage users and permissions
        entity: project
        policies:
          - projectAdmin
          - githubAdmin

    roles:
      - displayName: Owner
        technicalName: owner
        entityType: project
      - displayName: Member
        technicalName: member
        entityType: project
      - displayName: Vault Maintainer
        technicalName: vault_maintainer
        entityType: project

    policies:
      - displayName: Project Admin Policy
        technicalName: projectAdmin
        description: Policy to grant Project Administration rights on a particular Project in the context of the Organizations Service
      - displayName: Project Member Policy
        technicalName: projectMember
        description: Policy to grant Project Member rights on a particular Project in the context of the Organizations Service
      - displayName: Github Member
        technicalName: githubMember
        description: Policy to grants Member Access to the user in the DXP managed github team github
      - displayName: Github Admin
        technicalName: githubAdmin
        description: Policy to grants Admin Access to the user in the DXP managed github team github
