example-tenant:
  subdomain: test
  emailDomain: sap.com
tenant-123:
  subdomain: tenant123
  emailDomain: tenant123.com
  emailDomains:
    - tenant123.com
    - corp.tenant123.com
tenant-456:
  subdomain: tenant456
  emailDomain: tenant456.com
  emailDomains:
    - tenant456.com
    - corp.tenant456.com
tenant-789:
  subdomain: tenant789
  emailDomain: tenant789.com
  emailDomains:
    - tenant789.com
    - corp.tenant789.com