{{- if ((.Values).dataloader).enabled -}}
{{- $files := .Files }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-fga-schema
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
data:
  schema.fga: |
{{ $files.Get "assets/schema.fga" | indent 4}}
{{- end }}
