{{- if ((.Values).dataloader).enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-dataloader-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
{{- end }}