name: ci
on: [push]

jobs:
  pipe:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    uses: openmfp/gha/.github/workflows/pipeline-golang-app.yml@main
    secrets: inherit
    with:
      imageTagName: ghcr.io/openmfp/iam-service
      useTask: true
      useLocalCoverageConfig: true
